<h2>Part 1</h2>

**Import Pandas**

In [2]:
import pandas as pd

**Create a Series of Colours**

In [15]:
colours_series = pd.Series(['golden orange', 'orange', 'purple'], name="Colours")

In [16]:
colours_series

0    golden orange
1           orange
2           purple
Name: Colours, dtype: str

**Create a Series of Fruits**

In [17]:
fruits_series = pd.Series(['apricots', 'persimmons', 'figs'], name="Fruits")

In [18]:
fruits_series

0      apricots
1    persimmons
2          figs
Name: Fruits, dtype: str

**Merge them into a DataFrame**

In [19]:
df = pd.DataFrame({
    'Colours': colours_series,
    'Fruits': fruits_series
})

In [20]:
df

         Colours      Fruits
0  golden orange    apricots
1         orange  persimmons
2         purple        figs

<h2>Part 2</h2>

Extracting one of the columns from the DataFrame.

In [21]:
df["Fruits"]

0      apricots
1    persimmons
2          figs
Name: Fruits, dtype: str

Data type of the returned column.

In [22]:
type(df["Fruits"])

pandas.Series

Add a row to the DataFrame with a duplicate colour.

In [27]:
# len(df) -> finds the next available row index in the DataFrame
# .loc[...] -> assigns values to that row index.
df.loc[len(df)] = ["orange", "kumquat"]

Inspect the updated DataFrame.

In [28]:
df

         Colours      Fruits
0  golden orange    apricots
1         orange  persimmons
2         purple        figs
3         Yellow       Mango
4         orange     kumquat

Return only the rows that contain the duplicate colour.

In [29]:
# subset='Colours' checks duplicates inside the 'Colours' column.

# keep='first' marks everything after the first duplicate.
# keep='last' marks everything before the last duplicate.
# keep=False marks everything in the duplicate group.

# df[...] filters only the rows containing the duplicates.
df[df.duplicated(subset='Colours', keep=False)]

  Colours      Fruits
1  orange  persimmons
4  orange     kumquat