The Pandas Python library has a read_excel() function that accepts a string literal <br>
consisting of the path to the excel spreadsheet, and returns a DataFrame. <br>

Although read_excel() is being invoked with the dot operator, it is standalone, <br>
meaning that it is not called on an object. The dot operator is needed because <br>
it is defined inside the pandas module.

Supports the following file extensions read from a local file system or URL: <br>
xls, xlsx, xlsm, xlsb, odf, ods, and odt

Supports an option to read a single sheet or a list of sheets. <br>

Objective: <br>
Write a program that imports data from an excel spreadsheet and uses it to create a DataFrame.

In [1]:
import pandas as pd

./ means inside the current directory.

HDI_Table.xlsx is in the same directory as this program.

read_excel() will return a Pandas DataFrame.

In [44]:
df = pd.read_excel('./HDI_Table.xlsx')

Run the subsequent cell to analyze the DataFrame.

By default, the .head() method only reveals the first five rows in a DataFrame.

n=10 is a keyword argument because the name of the parameter "n"
is included.

This simply means show the first ten rows inside the DataFrame named "df".

Index 0 (zero) doesn't begin from where the column labels are because <br>
columns and rows are on their own different axes.

In [6]:
df.head(n=10)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
5,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
6,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
8,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
9,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2

Outputs the last ten rows in the DataFrame.

In [7]:
df.tail(10)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
266,NaN,GNI per capita rank minus HDI rank: Difference...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,HDI rank for 2020: Ranking by HDI value for 20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,Main data sources,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,Columns 1 and 7: HDRO calculations based on da...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

To view all of the rows in DataFrame:

"display.max_rows" controls the number of rows to display.

Passing None as the second argument removes the limit on the <br>
maximum number of rows that can be displayed.

In [8]:
pd.set_option("display.max_rows", None)

In [ ]:
df

Rows can be dropped from a dataset with the drop() method if they contain <br>
unwanted data: <br>
**data_frame_name.drop(index=data_frame_name.index[starting_row:ending_row], axis=0, inplace=True)**

Assigning 0 to the "axis" parameter means that rows will be dropped.

Assigning True to the "inplace" parameter will perform the operation in the <br>
original DataFrame rather than returning a copy of the updated DataFrame.

Drop the rows containing unwanted data.

Drop the first three rows from the DataFrame.

In [ ]:
# df.drop(index=df[:3], inplace=True)

Drop the row whose index is 0 (the first row by default).

In [45]:
df.drop(index=0, inplace=True)

Yes, 0 (zero) could have been included in the list located in the <br>
.drop() method in the next cell below, but the above command <br>
was just for demonstrating how a single row can be dropped.

In [46]:
# inplace=True specifies that the original DataFrame
# will have its data modified.

# Drop rows in index positions 1, 2, 4, 5, and 6.
df.drop([1, 2, 4, 5, 6], inplace=True)

In [ ]:
df

The reset_index() method is used to reset the index of <br>
a DataFrame to the default integer index (0, 1, 2, ...).

In [48]:
# Display all of the columns in the DataFrame.
df.columns

Index(['Back', 'Table 1. Human Development Index and its components ',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [17]:
# Display all of the rows in the DataFrame.
df.index

Index([  3,   7,   8,   9,  10,  11,  12,  13,  14,  15,
       ...
       266, 267, 268, 269, 270, 271, 272, 273, 274, 275],
      dtype='int64', length=270)

Extract the data from the first column.

In [ ]:
df['Table 1. Human Development Index and its components ']

Extract the value in the first row and second column.

In [28]:
# df.iloc[row_index, column_index]
df.iloc[6, 1]

'Denmark'

In [52]:
df.reset_index(drop=True, inplace=True)

In [30]:
df.head(n=10)

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
1,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
2,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
3,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2
4,4,"Hong Kong, China (SAR)",0.952,NaN,85.4734,d,17.27817,NaN,12.22621,NaN,62606.8454,NaN,6,NaN,4
5,5,Australia,0.951,NaN,84.5265,NaN,21.05459,c,12.72682,NaN,49238.43335,NaN,18,NaN,5
6,6,Denmark,0.948,NaN,81.3753,NaN,18.7148,c,12.96049,NaN,60364.78595,NaN,6,NaN,5
7,7,Sweden,0.947,NaN,82.9833,NaN,19.41853,c,12.60972,NaN,54489.37401,NaN,9,NaN,9
8,8,Ireland,0.945,NaN,81.9976,NaN,18.945221,c,11.582223,e,76168.98443,f,-3,NaN,8
9,9,Germany,0.942,NaN,80.6301,NaN,17.010139,NaN,14.090967,e,54534.21682,NaN,6,NaN,7

Construct a new DataFrame.

In [49]:
# Dictionary.

# Each key in the dictionary is the name of a column.
# Each value is the data in the column.

data_set = {
    # column_name: column_data
    'Countries': df['Table 1. Human Development Index and its components '],
    'Human Development Index (HDI)': df['Unnamed: 2'],
    'Life expectancy at birth': df['Unnamed: 4'],
    'Expected years of schooling': df['Unnamed: 6'],
    'Mean years of schooling': df['Unnamed: 8'],
    'Gross national income (GNI) per capita': df['Unnamed: 10']
}

df = pd.DataFrame(data=data_set)

In [50]:
df.head()

,Countries,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
3,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
7,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
8,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
9,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
10,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454

The keyword argument inplace=True modifies the original DataFrame <br>
as opposed to returning a new one.

In [53]:
df.drop(index=0, inplace=True)

By default, inplace is implicitly assigned False.

This means that a copy of the original DataFrame object is returned.

new_df will hold a reference to the copy which is the modified version <br>
of the DataFrame.

In [38]:
# new_df = df.drop(index=3)

In [54]:
df.head()

,Countries,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335

In [42]:
# new_df.head()

,Countries,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595
7,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401

Remove any row where one or more values is missing in the columns
listed.

Missing values are often (NaN).

Rows that have values like ".." will not be removed.

In [55]:
df.dropna(subset=[
    "Human Development Index (HDI)",
    "Life expectancy at birth",
    "Expected years of schooling",
    "Mean years of schooling",
    "Gross national income (GNI) per capita"
], inplace=True)

Scan the entire DataFrame.

In [56]:
pd.set_option("display.max_rows", None)

In [57]:
df

,Countries,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595
7,Sweden,0.947,82.9833,19.41853,12.60972,54489.37401
8,Ireland,0.945,81.9976,18.945221,11.582223,76168.98443
9,Germany,0.942,80.6301,17.010139,14.090967,54534.21682
10,Netherlands,0.941,81.6873,18.693165,12.58163,55979.411
11,Finland,0.94,82.0381,19.051929,12.87362,49452.16672
12,Singapore,0.939,82.7545,16.524321,11.92488,90918.64471
13,Belgium,0.937,81.8787,19.604219,12.37568,52293.39977
14,New Zealand,0.937,82.4513,20.28389,12.94469,44057.31394
15,Canada,0.936,82.6565,16.396259,13.834427,46807.98619
16,Liechtenstein,0.935,83.2575,15.18157,12.53854,146829.7006
17,Luxembourg,0.93,82.6287,14.39814,13.015192,84649.47467
18,United Kingdom,0.929,80.7422,17.309719,13.40612,45224.76564
19,Japan,0.925,84.7839,15.221626,13.3661,42274.29134
20,Korea (Republic of),0.925,83.6978,16.52174,12.51293,44500.93187
21,United States,0.921,77.1982,16.280979,13.68343,64765.21509
22,Israel,0.919,82.255,16.05089,13.344866,41523.74319
23,Malta,0.918,83.7769,16.83857,12.21026,38884.45623
24,Slovenia,0.918,80.6904,17.654921,12.80368,39746.01987
25,Austria,0.916,81.5797,16.007959,12.25669,53618.67138
26,United Arab Emirates,0.911,78.7104,15.71769,12.69403,62573.59181
27,Spain,0.905,83.01,17.916901,10.6054,38353.60164
28,France,0.903,82.4988,15.81207,11.61006,45937.05273
29,Cyprus,0.896,81.2033,15.64827,12.44017,38188.42152
30,Italy,0.895,82.8502,16.226789,10.74011,42839.51441
31,Estonia,0.89,77.1436,15.92896,13.54843,38048.26372
32,Czechia,0.889,77.7283,16.219681,12.86931,38745.21386
33,Greece,0.887,80.1106,20.02879,11.40853,29002.48545
34,Poland,0.876,76.4572,16.027149,13.16475,33033.96081
35,Bahrain,0.875,78.7605,16.29756,11.04659,39497.24788
36,Lithuania,0.875,73.7201,16.285061,13.4981,37931.30359
37,Saudi Arabia,0.875,76.936,16.13549,11.31053,46111.55135
38,Portugal,0.866,81.0443,16.871229,9.57594,33154.53343
39,Latvia,0.863,73.5786,16.20253,13.25272,32803.23423
40,Andorra,0.858,80.3684,13.300239,10.55512,51166.62661
41,Croatia,0.858,77.5804,15.1121,12.191084,30132.28814
42,Chile,0.855,78.9435,16.7313,10.934966,24563.24486
43,Qatar,0.855,79.2716,12.63722,9.996011,87134.13469
44,San Marino,0.853,80.8786,12.26614,10.80146,52653.82534
45,Slovakia,0.848,74.9101,14.51304,12.91142,30690.48552
46,Hungary,0.846,74.5301,15.033628,12.24959,32789.01063
47,Argentina,0.842,75.3899,17.87487,11.147269,20925.26814
48,Türkiye,0.838,76.0324,18.338221,8.63314,31032.80106
49,Montenegro,0.832,76.3426,15.08161,12.176483,20838.80129
50,Kuwait,0.831,78.6729,15.324433,7.328023,52919.76137
51,Brunei Darussalam,0.829,74.6424,13.95178,9.18,64489.53954
52,Russian Federation,0.822,69.419,15.76637,12.774288,27166.30891
53,Romania,0.821,74.1847,14.2299,11.27512,30027.29131
54,Oman,0.816,72.5406,14.57349,11.65404,27054.32505
55,Bahamas,0.812,71.5983,12.89945,12.641924,30486.18429
56,Kazakhstan,0.811,69.3622,15.765,12.347562,23942.81837
57,Trinidad and Tobago,0.81,72.9709,14.535453,11.610624,23392.02084
58,Costa Rica,0.809,77.0232,16.545771,8.80406,19974.27358
59,Uruguay,0.809,75.4356,16.8326,8.98255,21268.88122
60,Belarus,0.808,72.438,15.16997,12.14358,18848.96704
61,Panama,0.805,76.2233,13.057879,10.54059,26956.83707
62,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355
63,Georgia,0.802,71.694,15.56852,12.82222,14664.16825
64,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631
65,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747
66,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352
68,Albania,0.796,76.4626,14.448,11.286455,14131.11039
69,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595
70,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774
71,Barbados,0.79,77.5714,15.713385,9.852701,12306.341
72,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595
73,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775
74,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055
75,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465
76,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212
77,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117
78,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977
79,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283
80,China,0.768,78.2107,14.236115,7.600118,17504.39969
81,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037
82,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189
83,Palau,0.767,66.0204,15.78432,12.49143,13818.67869
84,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482
85,Peru,0.762,72.3769,15.387734,9.885519,12245.89366
86,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939
87,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498
88,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848
89,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666
90,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792
91,Maldives,0.747,79.9182,12.63561,7.322,15448.12788
92,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546
93,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456
94,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125
95,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155
96,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273
97,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532
98,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056
99,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477
100,Fiji,0.73,67.114,14.73679,10.921548,9980.110866
101,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033
102,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725
103,Dominica,0.72,72.814,13.319186,8.142186,11487.62422
104,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974
105,Libya,0.718,71.9112,12.85428,7.599985,15335.712
106,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286
107,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416
108,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381
109,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734
110,South Africa,0.713,62.341,13.64371,11.37316,12948.37325
111,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567
112,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374
113,Gabon,0.706,65.821,12.97731,9.436,13366.93455
114,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467
115,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836
116,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345
118,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468
119,Botswana,0.693,61.1409,12.265138,10.34,16198.31841
120,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194
121,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831
122,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621
123,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073
124,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427
125,Belize,0.683,70.4697,12.99169,8.8476,6309.099778
126,Morocco,0.683,74.0419,14.15191,5.916,7302.81917
127,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889
128,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595
129,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512
130,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199
131,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781
132,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899
133,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393
134,India,0.633,67.2398,11.87462,6.655109,6589.980037
135,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017
136,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945
137,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317
138,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034
139,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301
140,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815
141,Namibia,0.615,59.269,11.927207,7.192013,8633.504452
142,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617
143,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435
144,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633
145,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444
146,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873
147,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993
148,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154
149,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158
150,Angola,0.586,61.6434,12.1721,5.417391,5465.617791
151,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234
152,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893
153,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408
154,Kenya,0.575,61.427,10.698558,6.652,4473.570344
155,Congo,0.571,63.5187,12.330815,6.166,2889.283521
156,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739
157,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362
158,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119
159,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573
160,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711
161,Côte d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516
163,Tanzania (United Republic of),0.549,66.2007,9.22149,6.372899,2664.329096
164,Pakistan,0.544,66.0979,8.65835,4.53633,4623.70543
165,Togo,0.539,61.6194,12.950494,5.016807,2166.619062
166,Haiti,0.535,63.1924,9.7,5.554,2847.500746
167,Nigeria,0.535,52.676,10.127584,7.181074,4790.284425
168,Rwanda,0.534,66.0722,11.23097,4.425292,2209.795202
169,Benin,0.525,59.821,10.76668,4.304786,3408.965923
170,Uganda,0.525,62.7048,10.14987,5.730942,2181.43651
171,Lesotho,0.514,53.062,12.040878,6.010185,2700.435748
172,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064
173,Senegal,0.511,67.0926,8.96375,2.937938,3344.311825
174,Djibouti,0.509,62.3049,7.43298,4.1,5024.993944
175,Sudan,0.508,65.2667,7.945188,3.82,3575.19084
176,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983
177,Gambia,0.5,62.083,9.418626,4.637487,2172.207664
178,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604
179,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667
180,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.24159
181,Liberia,0.481,60.7472,10.42079,5.082,1288.74235
182,Congo (Democratic Republic of the),0.479,59.193,9.817864,7.018697,1076.098781
183,Afghanistan,0.478,61.9824,10.263844,2.98507,1824.190915
184,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579
185,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182
186,Yemen,0.455,63.7534,9.09871,3.2,1314.270189
187,Burkina Faso,0.449,59.2696,9.1421,2.114962,2117.915916
188,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924
189,Mali,0.428,58.9414,7.423038,2.31,2132.629443
190,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
191,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
192,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
193,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
194,South Sudan,0.385,54.9752,5.54251,5.72614,767.787
196,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
197,Monaco,..,85.9463,..,..,..
198,Nauru,..,63.617,11.69042,..,17729.74084
199,Somalia,..,55.2803,..,..,1017.96785
202,Very high human development,0.896,78.521301,16.506485,12.323006,43751.596458
203,High human development,0.754,74.709094,14.219287,8.327011,15167.24771
204,Medium human development,0.636,67.438318,11.944855,6.872257,6353.491965
205,Low human development,0.518,61.310991,9.459357,4.860214,3009.120913
207,Developing countries,0.685,69.866725,12.315912,7.545938,10703.751015
210,Arab States,0.708,70.89504,12.353535,8.02855,13500.556146
211,East Asia and the Pacific,0.749,75.57965,13.816818,7.839329,15580.43686
212,Europe and Central Asia,0.796,72.856526,15.446546,10.553922,19351.837024
213,Latin America and the Caribbean,0.754,72.09989,14.767956,8.9977,14520.661245
214,South Asia,0.632,67.85553,11.562208,6.710321,6481.393135
215,Sub-Saharan Africa,0.547,60.112467,10.267338,6.001639,3698.868914
217,Least developed countries,0.54,64.215856,10.182659,5.21532,2880.652487
218,Small island developing states,0.73,70.325547,12.422289,9.08964,16782.329527
220,Organisation for Economic Co-operation and Dev...,0.899,78.987605,16.459253,12.267755,45086.969067
222,World,0.732,71.365465,12.780907,8.617461,16752.082922

In [58]:
df.reset_index(drop=True, inplace=True)

Drop rows from the DataFrame beginning from index 191 to the end.

In [61]:
df.drop(df.index[191:], inplace=True)

See the last five rows in the DataFrame.

In [62]:
df.tail()

,Countries,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
186,Burundi,0.426,61.6627,10.722722,3.129267,731.786709
187,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611
188,Niger,0.4,61.5763,6.957112,2.116717,1239.866936
189,Chad,0.394,52.5254,8.035914,2.573774,1364.169417
190,South Sudan,0.385,54.9752,5.54251,5.72614,767.787

In [ ]:
# float(gni_per_capita) converts the string to a float.

# f"{...:,.0f}" formats the number with commas for
# thousands and 0 digits after the decimal.
df['Gross national income (GNI) per capita'] = df['Gross national income (GNI) per capita'].apply(
    lambda gni_per_capita: f"{float(gni_per_capita):,.0f}"
)

In [66]:
df.head()

,Countries,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
0,Switzerland,0.962,83.9872,16.500299,13.85966,"66,933"
1,Norway,0.961,83.2339,18.1852,13.00363,"64,660"
2,Iceland,0.959,82.6782,19.163059,13.76717,"55,782"
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,"62,607"
4,Australia,0.951,84.5265,21.05459,12.72682,"49,238"